"""Versioned prompts for the role-play feature."""

from .analyzer import TURN_ANALYZER_PROMPT_VERSION, TURN_ANALYZER_SYSTEM_PROMPT
from .customer import CUSTOMER_PROMPT_VERSION, CUSTOMER_SYSTEM_PROMPT
from .evaluator import EVALUATOR_PROMPT_VERSION, EVALUATOR_SYSTEM_PROMPT

__all__ = [
    "CUSTOMER_PROMPT_VERSION",
    "CUSTOMER_SYSTEM_PROMPT",
    "EVALUATOR_PROMPT_VERSION",
    "EVALUATOR_SYSTEM_PROMPT",
    "TURN_ANALYZER_PROMPT_VERSION",
    "TURN_ANALYZER_SYSTEM_PROMPT",
]
