"""Versioned prompts for the role-play feature."""

from .customer import CUSTOMER_PROMPT_VERSION, CUSTOMER_SYSTEM_PROMPT
from .evaluator import EVALUATOR_PROMPT_VERSION, EVALUATOR_SYSTEM_PROMPT

__all__ = [
    "CUSTOMER_PROMPT_VERSION",
    "CUSTOMER_SYSTEM_PROMPT",
    "EVALUATOR_PROMPT_VERSION",
    "EVALUATOR_SYSTEM_PROMPT",
]
